spring:
  datasource:
    url: jdbc:h2:mem:ewallet;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DEFAULT_NULL_ORDERING=HIGH
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level.org.flywaydb: info

app:
  security:
    jwtSecret: ${jwt_secret:dev-secret}

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always